import math

HEIGHT = 100
WIDTH = 100
LENGTH = 100
AGENT_RADIUS = 0.25
SECURITY_DISTANCE = 4
NUM_FLOORS = math.ceil(HEIGHT / (AGENT_RADIUS * 2 + SECURITY_DISTANCE))
NUM_ROWS = math.ceil(LENGTH / (AGENT_RADIUS * 2 + SECURITY_DISTANCE))
NUM_COLS = math.ceil(WIDTH / (AGENT_RADIUS * 2 + SECURITY_DISTANCE))
ALGORITHM_1 = "algorithm 1"
ALGORITHM_2 = "algorithm 2"